# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jannik Müller
email: hi@jannikmueller.com
description: Hi, i'm Jannik Müller, a berlin based Frontend Developer.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jannikmueller.com" # the base hostname & protocol for your site
twitter_username: JnnkMllr
github_username:  jnnkm
instagram_username: jannik_on_instagram 
xing_username: Jannik_Mueller2
linkedin_username: jannikmueller

# Build settings
markdown: kramdown